--- #target playbook
- hosts: 10.0.15.3
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: install httpd on linux
      action: yum name=httpd state=present
    - name: install docker on nodes
      action: yum name=docker state=present
